### ISSUE TITLE
Please update to latest version of loader-utils

### ISSUE THREAD

**Issue by naveedahmed1** [TheLarkInn/angular2-template-loader#75]
Please update to latest version of loader-utils, currently angular2-template-loader is using loader-utils@0.2.17, which doesnt seem to be compatible with some of the other plugins which are using latest version of loader-utils. For example angular-router-loader

**Comment by Gireeshk07** [comment]
@naveedahmed1 Did we get any fix for this issue. We are facing the same issue. Loader-utils 0.2.17 version has critical vulnerability, so we need to update to latest version of version which is 2.3.0. When we tried to update, we are seeing below error. I see this dependency didn't update from last 6 years. Is there any temporary fix for the issue?

`ERROR in .{projectpath}/spa/src/main.ts [INFO] Module build failed (from ./node_modules/angular2-template-loader/index.js): [INFO] Error: A valid query string passed to parseQuery should begin with '?' [INFO] at Object.parseQuery (node_modules/angular2-template-loader/node_modules/loader-utils/lib/parseQuery.js:13:11) [INFO] at Object.module.exports (node_modules/angular2-template-loader/index.js:21:27)` @Medevwithdesign 

@fjmorel Are we planning to merge this PR? We are facing this issue with parseQuery method. I think this PR will fix that issue?

**Comment by fjmorel** [comment]
It's not my repo so it's not up to me. There hasn't been a commit since 2017, so it's unlikely to get merged.

**Comment by Gireeshk07** [comment]
@fjmorel Do you know if we can have any alternate for angular2-template-loader that works as same and can replace in Angular project. 


@TheLarkInn Is it possible to merge this PR as it is causing issues with the older version of loader-utils.
