### ISSUE TITLE
DeprecationWarning from loaderUtils

### ISSUE THREAD

**Issue by unlight** [TheLarkInn/angular2-template-loader#85]
```
webpack@4.22.0
+-- angular2-template-loader@0.6.2
| `-- loader-utils@0.2.17
```
```
(node:6856) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (c:\Dev\sso\frontend.admin\node_modules\loader-utils\index.js:78:3)
    at Object.module.exports (c:\Dev\sso\frontend.admin\node_modules\angular2-template-loader\index.js:21:27)
```

**Comment by Gireeshk07** [comment]
@unlight Did we get any fix for this issue. We are facing the same issue. Loader-utils 0.2.17 version has critical vulnerability, so we need to update to latest version of version which is 2.3.0. When we tried to update, we are seeing below error. I see this dependency didn't update from last 6 years. Is there any temporary fix for the issue?

`ERROR in .{projectpath}/spa/src/main.ts
[INFO] Module build failed (from ./node_modules/angular2-template-loader/index.js):
[INFO] Error: A valid query string passed to parseQuery should begin with '?'
[INFO]     at Object.parseQuery (node_modules/angular2-template-loader/node_modules/loader-utils/lib/parseQuery.js:13:11)
[INFO]     at Object.module.exports (node_modules/angular2-template-loader/index.js:21:27)`

**Comment by unlight** [comment]
@Gireeshk07 
Use angular-cli (https://angular.io/cli)

**Comment by Medevwithdesign** [comment]
@unlight 

Is there any alternate to angular2-template-loader. Which can help in the same manner this dependency works ?

We tried @ngTools but that is not helpful in large project. And Errors for angular2-template-loader are different for different projects. Somewhere it is giving parse error and some places it miss the emoji.js
